# Site settings
title: Brian Carrigan
header-img: img/home-bg.jpg
email: brian.c.carrigan@gmail.com
description: "The personal blog of Brian Carrigan, software and electronics engineer."
baseurl: ""
url: "http://bcarrigan.com"
twitter_username: bcarrigan
github_username:  carrigan

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
